apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tafcpa-ingress
  namespace: tafcpa
  annotations:
    kubernetes.io/ingress.class: "traefik"  # ✅ Correct for Traefik in k3s
spec:
  ingressClassName: traefik  # ✅ Explicitly tell Kubernetes to use Traefik
  tls:
    - hosts:
        - tafcpa.sympli4.com
      secretName: sympli4-wildcard-cert # ✅ This must match your TLS secret
  rules:
  - host: tafcpa.sympli4.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service-tafcpa
            port:
              number: 80