apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: customer1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: jeremyanywhere/symp-nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80   # ✅ Added to allow HTTP -> HTTPS redirect
        - containerPort: 443  # ✅ Still allows HTTPS
      imagePullSecrets:
      - name: my-dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: customer1
spec:
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP  # ✅ Correct for Ingress